// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raftlog.proto

/*
Package raftlog_pb is a generated protocol buffer package.

It is generated from these files:
	raftlog.proto

It has these top-level messages:
	LBO
*/
package raftlogpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import raftpb "github.com/coreos/etcd/raft/raftpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LBO struct {
	Offset           *int64        `protobuf:"varint,1,req,name=offset" json:"offset,omitempty"`
	Size             *uint32       `protobuf:"varint,2,req,name=size" json:"size,omitempty"`
	Entry            *raftpb.Entry `protobuf:"bytes,3,req,name=entry" json:"entry,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *LBO) Reset()                    { *m = LBO{} }
func (m *LBO) String() string            { return proto.CompactTextString(m) }
func (*LBO) ProtoMessage()               {}
func (*LBO) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LBO) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *LBO) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *LBO) GetEntry() *raftpb.Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*LBO)(nil), "raftlog_pb.LBO")
}

func init() { proto.RegisterFile("raftlog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x4c, 0x2b,
	0xc9, 0xc9, 0x4f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x82, 0x72, 0xe3, 0x0b, 0x92,
	0xa4, 0xc0, 0x6c, 0x88, 0xb8, 0x52, 0x18, 0x17, 0xb3, 0x8f, 0x93, 0xbf, 0x90, 0x18, 0x17, 0x5b,
	0x7e, 0x5a, 0x5a, 0x71, 0x6a, 0x89, 0x04, 0xa3, 0x02, 0x93, 0x06, 0x73, 0x10, 0x94, 0x27, 0x24,
	0xc4, 0xc5, 0x52, 0x9c, 0x59, 0x95, 0x2a, 0xc1, 0xa4, 0xc0, 0xa4, 0xc1, 0x1b, 0x04, 0x66, 0x0b,
	0x29, 0x73, 0xb1, 0xa6, 0xe6, 0x95, 0x14, 0x55, 0x4a, 0x30, 0x2b, 0x30, 0x69, 0x70, 0x1b, 0xf1,
	0xea, 0x81, 0x8c, 0x2b, 0x48, 0xd2, 0x73, 0x05, 0x09, 0x06, 0x41, 0xe4, 0x00, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0x9b, 0xe4, 0xf9, 0x7f, 0x00, 0x00, 0x00,
}
